name: Build Pull Request
on: pull_request
permissions:
  contents: read
jobs:
  build:
    name: Build Pull Request
    runs-on: ${{ vars.UBUNTU_MEDIUM || 'ubuntu-latest' }}
    steps:
      - name: Check Out Code
        uses: actions/checkout@v4
      # This enables task distribution via Nx Cloud
      # Run this command as early as possible, before dependencies are installed
      # Learn more at https://nx.dev/ci/reference/nx-cloud-cli#npx-nxcloud-startcirun
      # Uncomment this line to enable task distribution
      - run: NX_CLOUD_RETRIEVAL_CONCURRENCY=8 NX_PERF_LOGGING=true NX_VERBOSE_LOGGING=true npx nx-cloud start-ci-run --distribute-on="8 linux-medium-jvm"
      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 22
          check-latest: true
          cache: npm
      - run: npm install
      - name: Build
        id: build
        uses: ./.github/actions/build
      - name: Print JVM Thread Dumps When Cancelled
        if: cancelled()
        uses: ./.github/actions/print-jvm-thread-dumps
      - name: Upload Build Reports
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-reports
          path: '**/build/reports/'
